Updated with tutorial
zscaler/zpa-terraform-consul-webinar pull request #1
Opened 2023-06-28 16:01 UTC by im2nguyen

2023-07-03 04:25 UTC, willguibr requested changes
Change to: This repository will provision Zscaler Private Access App Connector, Consul & NGINX servers in AWS. Optionally, you can also deploy a Vault Cluster to store your ZPA API credentials, so Consul can authenticate to the ZPA Cloud.

2023-07-03 04:25 UTC, willguibr commented on README.md
> +This repository will provision Zscaler Private Access App Connector, Consul & NGINX servers in AWS. Optionally, you can also deploy a Vault Cluster in store the API credentials, so Consul can authent
**Change to:** This repository will provision Zscaler Private Access App Connector, Consul & NGINX servers in AWS. Optionally, you can also deploy a Vault Cluster to store your ZPA API credentials, so Consul can authenticate to the ZPA Cloud.

2023-07-03 04:28 UTC, im2nguyen commented on README.md
> +This repository will provision Zscaler Private Access App Connector, Consul & NGINX servers in AWS. Optionally, you can also deploy a Vault Cluster in store the API credentials, so Consul can authent
```suggestion
This repository will provision Zscaler Private Access App Connector, Consul & NGINX servers in AWS. Optionally, you can also deploy a Vault Cluster to store your ZPA API credentials, so Consul can authenticate to the ZPA Cloud.
```

2023-07-06 06:15 UTC, im2nguyen commented on README.md
> +This scenario will trigger CTS by increasing the number of servers allocated to the autoscaling group. CTS will update the BIG-IP configuration to include the new NGINX instances created by increasin
```suggestion
This scenario will trigger CTS by increasing the number of servers allocated to the autoscaling group. CTS will update the ZPA application segment configuration to include the new NGINX instances created by increasing the autoscaling group capacity.
```

2023-07-06 06:15 UTC, im2nguyen commented on README.md
> +CTS will detect the change from the Consul catalog and modify the BIG-IP configuration to reflect the new `web-server` instances.
```suggestion
CTS will detect the change from the Consul catalog and update the application segments to reflect the new `web` services.
```

2023-07-06 14:09 UTC, merged